### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by pdpinch** [mitodl/PyLmod#72]
pip appears to be having a problem with https://github.com/mitodl/PyLmod/blob/master/setup.py#L61

```
$ pip install pylmod
You are using pip version 7.0.0, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting pylmod
  Downloading pylmod-0.2.0.tar.gz
Collecting requests>=2.5.1 (from pylmod)
  Downloading requests-2.11.1-py2.py3-none-any.whl (514kB)
    100% |████████████████████████████████| 516kB 710kB/s 
Building wheels for collected packages: pylmod
  Running setup.py bdist_wheel for pylmod
  Complete output from command /Users/pdpinch/Documents/Engineering/repos/PyLmod/venv/bin/python -c "import setuptools;__file__='/private/var/folders/3h/synj72qx02l55_lxv08l7x1h0000gn/T/pip-build-5qOh2E/pylmod/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/3h/synj72qx02l55_lxv08l7x1h0000gn/T/tmpmUzORMpip-wheel-:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/pylmod
  copying pylmod/__init__.py -> build/lib/pylmod
  copying pylmod/base.py -> build/lib/pylmod
  copying pylmod/exceptions.py -> build/lib/pylmod
  copying pylmod/gradebook.py -> build/lib/pylmod
  copying pylmod/membership.py -> build/lib/pylmod
  creating build/lib/pylmod/tests
  copying pylmod/tests/__init__.py -> build/lib/pylmod/tests
  copying pylmod/tests/common.py -> build/lib/pylmod/tests
  copying pylmod/tests/test_base.py -> build/lib/pylmod/tests
  copying pylmod/tests/test_gradebook.py -> build/lib/pylmod/tests
  copying pylmod/tests/test_membership.py -> build/lib/pylmod/tests
  copying pylmod/tests/test_module.py -> build/lib/pylmod/tests
  running egg_info
  writing requirements to pylmod.egg-info/requires.txt
  writing pylmod.egg-info/PKG-INFO
  writing top-level names to pylmod.egg-info/top_level.txt
  writing dependency_links to pylmod.egg-info/dependency_links.txt
  warning: manifest_maker: standard file '-c' not found

  reading manifest file 'pylmod.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'pylmod.egg-info/SOURCES.txt'
  installing to build/bdist.macosx-10.12-intel/wheel
  running install
  running install_lib
  creating build/bdist.macosx-10.12-intel
  creating build/bdist.macosx-10.12-intel/wheel
  creating build/bdist.macosx-10.12-intel/wheel/pylmod
  copying build/lib/pylmod/__init__.py -> build/bdist.macosx-10.12-intel/wheel/pylmod
  copying build/lib/pylmod/base.py -> build/bdist.macosx-10.12-intel/wheel/pylmod
  copying build/lib/pylmod/exceptions.py -> build/bdist.macosx-10.12-intel/wheel/pylmod
  copying build/lib/pylmod/gradebook.py -> build/bdist.macosx-10.12-intel/wheel/pylmod
  copying build/lib/pylmod/membership.py -> build/bdist.macosx-10.12-intel/wheel/pylmod
  creating build/bdist.macosx-10.12-intel/wheel/pylmod/tests
  copying build/lib/pylmod/tests/__init__.py -> build/bdist.macosx-10.12-intel/wheel/pylmod/tests
  copying build/lib/pylmod/tests/common.py -> build/bdist.macosx-10.12-intel/wheel/pylmod/tests
  copying build/lib/pylmod/tests/test_base.py -> build/bdist.macosx-10.12-intel/wheel/pylmod/tests
  copying build/lib/pylmod/tests/test_gradebook.py -> build/bdist.macosx-10.12-intel/wheel/pylmod/tests
  copying build/lib/pylmod/tests/test_membership.py -> build/bdist.macosx-10.12-intel/wheel/pylmod/tests
  copying build/lib/pylmod/tests/test_module.py -> build/bdist.macosx-10.12-intel/wheel/pylmod/tests
  running install_egg_info
  Copying pylmod.egg-info to build/bdist.macosx-10.12-intel/wheel/pylmod-0.2.0-py2.7.egg-info
  running install_scripts
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/3h/synj72qx02l55_lxv08l7x1h0000gn/T/pip-build-5qOh2E/pylmod/setup.py", line 72, in <module>
      zip_safe=True,
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/Users/pdpinch/Documents/Engineering/repos/PyLmod/venv/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 228, in run
      self.distinfo_dir)
    File "/Users/pdpinch/Documents/Engineering/repos/PyLmod/venv/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 393, in egg2dist
      distribution=self.distribution)
    File "/Users/pdpinch/Documents/Engineering/repos/PyLmod/venv/lib/python2.7/site-packages/wheel/metadata.py", line 164, in pkginfo_to_dict
      new_requirements = list(convert_requirements(requirements))
    File "/Users/pdpinch/Documents/Engineering/repos/PyLmod/venv/lib/python2.7/site-packages/wheel/metadata.py", line 219, in convert_requirements
      parsed_requirement = pkg_resources.Requirement.parse(req)
    File "/Users/pdpinch/Documents/Engineering/repos/PyLmod/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2981, in parse
      raise ValueError("No requirements found", s)
  ValueError: ('No requirements found', '\n')

  ----------------------------------------
  Failed building wheel for pylmod
Failed to build pylmod
Installing collected packages: requests, pylmod
  Running setup.py install for pylmod
Successfully installed pylmod-0.2.0 requests-2.11.1
```

**Comment by jolyonb** [comment]
I actually get a different error.

```
test $ virtualenv env
sNew python executable in /Users/jolyon/test/env/bin/python
Installing setuptools, pip, wheel...done.
test $ source env/bin/activate
(env) test $ pip install pylmod
Collecting pylmod
  Using cached pylmod-0.2.0.tar.gz
Collecting requests>=2.5.1 (from pylmod)
  Using cached requests-2.11.1-py2.py3-none-any.whl
Building wheels for collected packages: pylmod
  Running setup.py bdist_wheel for pylmod ... error
  Complete output from command /Users/jolyon/test/env/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/mx/gl28gdx95l904ntbd0_9jy0h0000gq/T/pip-build-kR7AVB/pylmod/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/mx/gl28gdx95l904ntbd0_9jy0h0000gq/T/tmpbCxHjkpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/pylmod
  copying pylmod/__init__.py -> build/lib/pylmod
  copying pylmod/base.py -> build/lib/pylmod
  copying pylmod/exceptions.py -> build/lib/pylmod
  copying pylmod/gradebook.py -> build/lib/pylmod
  copying pylmod/membership.py -> build/lib/pylmod
  creating build/lib/pylmod/tests
  copying pylmod/tests/__init__.py -> build/lib/pylmod/tests
  copying pylmod/tests/common.py -> build/lib/pylmod/tests
  copying pylmod/tests/test_base.py -> build/lib/pylmod/tests
  copying pylmod/tests/test_gradebook.py -> build/lib/pylmod/tests
  copying pylmod/tests/test_membership.py -> build/lib/pylmod/tests
  copying pylmod/tests/test_module.py -> build/lib/pylmod/tests
  running egg_info
  writing requirements to pylmod.egg-info/requires.txt
  writing pylmod.egg-info/PKG-INFO
  writing top-level names to pylmod.egg-info/top_level.txt
  writing dependency_links to pylmod.egg-info/dependency_links.txt
  warning: manifest_maker: standard file '-c' not found
  
  reading manifest file 'pylmod.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'pylmod.egg-info/SOURCES.txt'
  installing to build/bdist.macosx-10.11-intel/wheel
  running install
  running install_lib
  creating build/bdist.macosx-10.11-intel
  creating build/bdist.macosx-10.11-intel/wheel
  creating build/bdist.macosx-10.11-intel/wheel/pylmod
  copying build/lib/pylmod/__init__.py -> build/bdist.macosx-10.11-intel/wheel/pylmod
  copying build/lib/pylmod/base.py -> build/bdist.macosx-10.11-intel/wheel/pylmod
  copying build/lib/pylmod/exceptions.py -> build/bdist.macosx-10.11-intel/wheel/pylmod
  copying build/lib/pylmod/gradebook.py -> build/bdist.macosx-10.11-intel/wheel/pylmod
  copying build/lib/pylmod/membership.py -> build/bdist.macosx-10.11-intel/wheel/pylmod
  creating build/bdist.macosx-10.11-intel/wheel/pylmod/tests
  copying build/lib/pylmod/tests/__init__.py -> build/bdist.macosx-10.11-intel/wheel/pylmod/tests
  copying build/lib/pylmod/tests/common.py -> build/bdist.macosx-10.11-intel/wheel/pylmod/tests
  copying build/lib/pylmod/tests/test_base.py -> build/bdist.macosx-10.11-intel/wheel/pylmod/tests
  copying build/lib/pylmod/tests/test_gradebook.py -> build/bdist.macosx-10.11-intel/wheel/pylmod/tests
  copying build/lib/pylmod/tests/test_membership.py -> build/bdist.macosx-10.11-intel/wheel/pylmod/tests
  copying build/lib/pylmod/tests/test_module.py -> build/bdist.macosx-10.11-intel/wheel/pylmod/tests
  running install_egg_info
  Copying pylmod.egg-info to build/bdist.macosx-10.11-intel/wheel/pylmod-0.2.0-py2.7.egg-info
  running install_scripts
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/mx/gl28gdx95l904ntbd0_9jy0h0000gq/T/pip-build-kR7AVB/pylmod/setup.py", line 72, in <module>
      zip_safe=True,
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/Users/jolyon/test/env/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 252, in run
      self.distinfo_dir)
    File "/Users/jolyon/test/env/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 419, in egg2dist
      distribution=self.distribution)
    File "/Users/jolyon/test/env/lib/python2.7/site-packages/wheel/metadata.py", line 178, in pkginfo_to_dict
      new_requirements = sorted(convert_requirements(requirements))
    File "/Users/jolyon/test/env/lib/python2.7/site-packages/wheel/metadata.py", line 233, in convert_requirements
      parsed_requirement = pkg_resources.Requirement.parse(req)
    File "/Users/jolyon/test/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2902, in parse
      req, = parse_requirements(s)
  ValueError: need more than 0 values to unpack
  
  ----------------------------------------
  Failed building wheel for pylmod
  Running setup.py clean for pylmod
Failed to build pylmod
Installing collected packages: requests, pylmod
  Running setup.py install for pylmod ... done
Successfully installed pylmod-0.2.0 requests-2.11.1
```
